### PR TITLE
Make unzip installation optional

### PR DESCRIPTION
**Pull request by daylicron**
Hello Dario,

in my company we define in the baseline that unzip is installed on every server. Therefore I had to add an option to the module to optionally disable the installation of unzip.

Cheers
Dennis

### CODE REVIEW

**Comment by dsestero** [comment]
Hi Dennis,

thanks for the pull request but please answer me this question: the reason I included the download_uncompres::dependencies class in manifests/init.pp was that if the package is already installed it should not cause any problems. Is this assumption wrong?

Ciao,
Dario

**Comment by daylicron** [comment]
Hi Dario,

unfortunately in our case this didn't work. Puppet threw the error that the installation of unzip can't be defined two times. We define it in baseline/default.pp
`$common_packages = [... "unzip", ...]`
`ensure_packages($common_packages, { 'ensure' => 'latest' })`
 that's why I implemented the switch.

Cheers
Dennis

**Comment by dsestero** [comment]
Hi Dennis,

thanks for the pull request but please answer me this question: the reason I included the download_uncompres::dependencies class in manifests/init.pp was that if the package is already installed it should not cause any problems. Is this assumption wrong?

Ciao,
Dario

**Comment by dsestero** [comment]
Hi Dennis,
I released version 1.3.2 on PuppetForge adding a little change after merging your pull request in order to make the module work with both Puppet 3 and Puppet 4/5.

Ciao,
Dario

**Comment by daylicron** [comment]
Hi Dario,

good job. Thank you very much!

Cheers
Dennis

**Pull request merged**
